---
apiVersion: v1
kind: Namespace
metadata:
  name: artwork-video
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: force
    component: web
    layer: application
  name: force-web
  namespace: artwork-video
spec:
  selector:
    matchLabels:
      app: force
      component: web
      layer: application
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: force
        component: web
        layer: application
      name: force-web
      namespace: default
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
      containers:
      - env:
        - name: PORT
          value: '5000'
        - name: DD_TRACE_AGENT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PAGE_CACHE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KEEPALIVE_TIMEOUT_SECONDS
          value: '95'
        - name: HEADERS_TIMEOUT_SECONDS
          value: '105'
        envFrom:
        - configMapRef:
            name: force-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/force:staging
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 35
        name: force-web
        ports:
        - containerPort: 5000
          name: force-http
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: X-FORWARDED-PROTO
              value: https
            path: /system/up
            port: force-http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: 1.5Gi
          requests:
            cpu: 100m
            memory: 1Gi
      dnsConfig:
        options:
        - name: ndots
          value: '1'
      dnsPolicy: ClusterFirst
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: force-web
  namespace: artwork-video
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1800
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: force-web
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: force
    component: web
    layer: application
  name: force-web-internal
  namespace: artwork-video
spec:
  ports:
  - name: force-http
    port: 5000
    protocol: TCP
    targetPort: force-http
  selector:
    app: force
    component: web
    layer: application
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,172.64.0.0/13,131.0.72.0/22,104.16.0.0/13,104.24.0.0/14
  name: force
  namespace: artwork-video
spec:
  ingressClassName: nginx
  rules:
  - host: staging.artsy.net
    http:
      paths:
      - backend:
          serviceName: force-web-internal
          servicePort: force-http
        path: /
        pathType: Prefix
